### ISSUE TITLE
dockerfile is old and having some question

### ISSUE THREAD

**Issue by jinri** [saule1508/pgcluster#7]
1、postgres/Dockerfile   pgpool/Dockerfile   from is not same
2、pgpool/Dockerfile rm -rf /var/cache/yum is wrong,should  /var/yum/cache
3、RUN yum install -y https://download.postgresql.org/pub/repos/yum/${MAJORVER}/redhat/rhel-7-x86_64/pgdg-centos${MAJORVER}-${MAJORVER}-${MINORVER}.noarch.rpm is missing

**Comment by saule1508** [comment]
I am not using postgres and pgpool at the moment (unfortunately, I am working now for a company using Oracle) so I don't maintain this repo actively.

But I will take the time to bump the versions, I guess pgpool and repmgr have evolved since then. Also my version of node and react might be old.

I am using Fedora at home and the first issue what that docker does not run anymore on Fedora, there is a work-around though (revert cgroups to v1) so I got it running on my desktop.

**Comment by saule1508** [comment]
I upgraded pgppool and nodejs image to centos8, postgres to 11.7, pgpool to 4.1.1 and repmgr to 5 and nodejs to 12. I could still upgrade postgres image to centos8 and postgres 12. Also upgrading react-create-app in the nodejs application would be nice.

**Comment by saule1508** [comment]
I upgraded postgres image to centos 8 and postgres to version 12. There was some issues because supervisorctl is now in /usr/local/bin and this is not in the path when doing sudo.
I did basic testing and it works
